### ISSUE TITLE
Incorrect Calculation of Average

### ISSUE THREAD

**Issue by girantinas** [RoanH/osu-BonusPP#1]
Average should be the sum of all values divided by the amount of all values.
https://github.com/RoanH/osu-BonusPP/blob/69d6691a89345c47398e67b5cf293c6bad25813f/BonusPP/src/me/roan/bonuspp/BonusPP.java#L231-L238
In the above code, avgX will always equal 1. But, let's say there's 100 scores, then if the first is x=1, second is x=2, etc, which means the average should be 50.5 (Sum of first 100 integers / 100). So why is there such a mismatch and does it matter?

**Comment by RoanH** [comment]
That so stupid... I can't believe I never caught that one...

Yes you are correct the average x value should of course be the average x value...
Which would normally be 49.5 since we start counting at 0.

As for whether it matters or not, it depends. The majority of players does not have enough scores outside of their top 100 that are high enough to add up to a significant change and the current wrong implementation still does a somewhat okay job (though the scores it finds are significantly lower than the ones you'd actually expect, but at the same time it kinda makes up for that by computing infinitely many of them).

So then in light of all this I'm going to make two changes:
- Properly compute the average...
- Bound the number of extra scores by the users playcount instead of infinity.

All things considered though I don't expect any users to gain more than 10 bonus pp because of this change.

Also noticed that WubWoofWolf (who got calculated at exactly 416 bonus pp when I released this program) is starting to climb above the normal bonuspp cap. So since I'm going to be looking into this anyway I'm going to look for more accuracy improvements / calculation issues too.

Thank you for taking the time to review the math ^^

P.S. Should be noted that for most player (scores on <2000 ranked maps) this error is probably negligible. I ran some tests against WubWoofWolf and fixing that error only gave him 7 more bonus pp, although that puts him well above the expected maximum value...

**Comment by girantinas** [comment]
Yeah the reason I was curious was because I also ran tests on WWW as an extreme case and saw that with n=1 and avgX=(N+1)/2 and n=0 and avgX=(N-1)/2 , both results were worse, so I thought there was some reason for this.

**Comment by RoanH** [comment]
With only the top 100 scores to work with all you can do try to guess the value for all the other scores. But it seems that even with this extra polation of scores we're still short of the actual non bonus pp value of a player (though it still works rather well since without extra polation WWW ends up at 469 bonuspp).

I might look into switching to some other regression form (since linear really isn't the best for this) to get the regression to level off slower. It should help somewhat as my tests show that manually setting the coefficient for the linear regression to 0 yields WWW 415 bonus pp so some 1/x or 1/sqrt(x) function might work rather well. If I have the time I'll experiment with this a bit.

**Comment by girantinas** [comment]
Alright. Would you say the older version with the avgX=1 gives better results? If so, I'd like to PR it to osu-tools because their bonus pp calculation is currently a bit off. The problem is I don't know how I would justify this mistake.

**Comment by RoanH** [comment]
avgX=1 while appearing better is just plain wrong and really has no justification. The only way to truely compute bonus pp is by fetching all the top scores for a certain user, but that's just inefficient. I have quite high hopes for different regression models though and _hope_ to be able to look into them the upcoming weekend. Personally I'd hold off on a PR until I've found a better regression model, but that's easy for me to say since I wouldn't have to wait ¯\\\_(ツ)\_/¯ . From the testing I did just now I found that it is not possible to implement linear regression in such a way that there are no cases where the bonus pp amount goes over 416. However it seems plausible that a different regression model could actually accomplish this.

**Comment by girantinas** [comment]
I'll try regression in the form of y = c0 + c1/x and see how that works out.

**Comment by RoanH** [comment]
Sounds good, let me know if you find anything interesting ^^

**Comment by girantinas** [comment]
Alright so I did least squares on y = c0 + c1z then said z = 1/x and I got WWW's bonus as 414.2 . Either I have to do it properly (do least squares directly on y = c0 + c1/x) or I might need 1/x^2 or some other curve.

**Comment by girantinas** [comment]
Alright Gauss-Newton on y = c0 + c1/x also gives the same value for WWW's bonus. Ae^(-bx) + C might be better?

Edit: The Gauss-Newton for the reciprocal curve is the same for all bonuses as linear modeling with z=1/x

**Comment by girantinas** [comment]
Seems like c0 - c1logx or c0 + c1/log(x+1) seem like good candidates (starting indices at 1 instead of 0)

**Comment by RoanH** [comment]
Completely forgot about logarithms >_> those indeed look like they could work well too.

Haven't actually had the time yet to investigate this indepth yet, some other issues too longer than I expected. Currently though this has the highest priority on my todo list for public projects so I hope to get to it pretty soon.

**Comment by RoanH** [comment]
So I started running some tests with `c0 + c1 * x + c2/ln(c3 * x + 1)`.
Then after minimizing the error on a few users I found that `c1` would always get set to 0 eventually.
So I took out the term and minized some more after which `c0` would go to 0 eventually.
The left `c2/ln(c3 * x + 1)` seems to do a rather good job, but even with that I still end up with 415.6696 bonus pp for WWW instead of the expected 416.6667. It's a lot better, but by no means perfect. Notable is that the predicted values seem to level off faster than the real values would suggest. So improving that would be the next step. For that changing the base of the logarithm shouldn't matter as `c2` already accounts for it. Which means a different formula is probably required again :/
![afbeelding](https://user-images.githubusercontent.com/8530896/52452458-4d3a9980-2b43-11e9-8f5f-a7b07b9cdb7b.png)

**Comment by girantinas** [comment]
Just curious, what algorithm did you use that made the constants go to 0? A better initial value will compensate better under some algorithms.

**Comment by RoanH** [comment]
I used the GRG non linear solver, since I'm mainly still looking for a formula that works well so I don't mind a bit more manual effort for now. It's basically just a convergence algorithm. But for all the users I went through those two variables would always end up as 0.

**Comment by RoanH** [comment]
Sorry for the slow progress on this, but I quite suddenly had a lot of deadlines to handle on non-personal projects >_>

I currently have a rather nice implementation, but I can't seem to be able to find a good algorithm to get both WWW and Xasuma close to the maximum value (I suppose I'm hitting the limits of what regression can do here). The values are rather good though with most users I've tested that for sure have the maximum bonus pp amount being off by less than 0.5pp.

WWW: 416.705886606087
Xasuma: 415.7655351593785
Andrea: 416.2265325351482
Sure: 416.1236477075645
Morimiya Aono: 416.285215025212
Arx Alveria: 416.1130756099883

I'll most likely go with this implementation and write up a short explanation if you're interested in that.

**Comment by girantinas** [comment]
Ok sounds good. These results are pretty nice (except xasuma is a bit off, but w/e).

**Comment by RoanH** [comment]
Yeah Xasuma and WWW gave me a lot of trouble. They would always differ in bonus pp amount by at least 1 pp.

> Basic outline of the algorithm:
> 1. Transform all the data points to their weighted form using the equation `y = x*0.95^i`.
> 2. Transform all the data points again by taking the base 100 logarithm of them.
> 3. Assign a weight to each of the data points based on their ordered location using `w = ln(x + 2)`.
> 4. Perform linear regression on the resultant data set.
> 5. Compute new scores using the regression model.
> 6. Transform all the computed data points by raising 100 to them `y = 100^x`.
